# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name : Default

steps:
- task: UsePythonVersion@0
  inputs:
     versionSpec: '3.x'
     addToPath: true
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: |
   python -m pip install --upgrade pip
   python install Flask
  displayName: 'Installed dependencies'
- script: |
    pyhon -m flask --version
    python app.py &
  displayName: 'Run Flask app'
- script: |
   curl http://localhost\:5000
  displayName: 'Test app'
