# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name : Default

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec:'3.x'
      addToPath: true
      
   - script: |
      python -m pip install --upgrade pip
      pip install Flask
      displayName: 'Install dependencies'
   - script: |
      python -m flask --version
      python app.py &
      displayName: 'Run Flask app'

   - script: |
       curl http://localhost:5000
    displayName: 'Test app'
